[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
evm_version = "shanghai"
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]

[profile.ci]
fuzz = { runs = 10_000 }
invariant = { runs = 1_000, depth = 20, fail_on_revert = false }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[doc]
out = "docs"
title = "Agent Receiver Documentation"

[dependencies]
forge-std = { git = "https://github.com/foundry-rs/forge-std", version = "v1.8.0" }
openzeppelin-contracts = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts", version = "v5.0.2" }
wormhole-solidity-sdk = { git = "https://github.com/wormhole-foundation/wormhole-solidity-sdk", version = "v0.2.1" }