[features]
seeds = false
skip-lint = false

[programs.localnet]
orb_forge = "FoRGe11111111111111111111111111111111111111"

[programs.devnet]
orb_forge = "FoRGe11111111111111111111111111111111111111"

[programs.mainnet]
orb_forge = "FoRGe11111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"